name: adversarial-detection
channels:
  - defaults
dependencies:
  - flask=1.1.2
  - flask-cors=3.0.10
  - pillow=8.3.1
  - pip=21.1.3
  - python=3.8.0
  - pip:
    - eventlet==0.29.1
    - flask-socketio==4.3.1
    - keras==2.4.3
    - numpy==1.21.1
    - opencv-python==4.5.3.56
    - python-socketio==4.6.0
    - scipy==1.4.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - websocket-client==1.1.0
