name: adversarial-detection
channels:
  - defaults
dependencies:
  - bidict=0.21.2
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - click=8.0.1
  - flask=1.1.2
  - flask-cors=3.0.10
  - freetype=2.10.4
  - importlib-metadata=3.10.0
  - itsdangerous=2.0.1
  - jinja2=3.0.1
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.3.1
  - pip=21.1.3
  - python=3.8.0
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - astunparse==1.6.3
    - cachetools==4.2.2
    - charset-normalizer==2.0.3
    - colorama==0.4.4
    - dnspython==1.16.0
    - eventlet==0.29.1
    - flask-socketio==4.3.1
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.33.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - greenlet==1.1.0
    - grpcio==1.38.1
    - h5py==2.10.0
    - idna==3.2
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.21.1
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-engineio==3.13.2
    - python-socketio==4.6.0
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.4.1
    - tdqm==0.0.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - tqdm==4.61.2
    - urllib3==1.26.6
    - websocket-client==1.1.0
    - wrapt==1.12.1
