name: adversarial-detection-gpu
channels:
  - defaults
dependencies:
  - flask=1.1.2
  - flask-cors=3.0.10
  - pillow=8.3.1
  - pip=21.1.3
  - python=3.8.0
  - cudnn
  - cudatoolkit
  - tensorflow-gpu=2.4.1
  - h5py=2.10.0
  - keras=2.4.3
  - pip:
    - eventlet==0.29.1
    - flask-socketio==4.3.1
    - opencv-python==4.5.3.56
    - python-socketio==4.6.0
    - python-engineio==3.13.2
    - setuptools==52.0.0
    - scipy==1.4.1
    - websocket-client==1.1.0
