name: adversarial-detection
channels:
  - defaults
dependencies:
  - flask=1.1.2
  - flask-cors=3.0.10
  - python=3.8.0
  - pip
  - pillow=8.3.1
  - pip:
    - eventlet==0.29.1
    - flask-socketio==4.3.1
    - h5py==2.10.0
    - keras==2.4.3
    - numpy
    - opencv-python==4.5.3.56
    - python-socketio==4.6.0
    - python-engineio==3.13.2
    - scipy==1.4.1
    - tensorflow==2.4.1
    - websocket-client==1.1.0
